'use strict';

var Validators = require( './validators/Validators' );

/**
 * Constructor for value type. The value type defines what validators can be used on a value of the
 * type.
 *
 * @param {string} typeName The name of the type.
 *
 * @constructor
 */
module.exports = function TypeSpec( name ) {
	var self = this;

	var using = [];
	var descriptors = [];
	var validators = new Validators();
	var properties = {};

	if( typeof name !== 'string' || name.length < 1 ) {
		throw new Error( ' No name given for this type' );
	}

	/**
	 * Returns the type's name.
	 *
	 * @returns {string}
	 */
	this.name = function () {
		return name;
	};

	/**
	 * Allows to define some sort of constructor for values of this type. The callback function
	 * has access to descriptors required for instances of this type.
	 *
	 * @param {Function} fn
	 * @returns {TypeSpec} self-reference
	 */
	this.use = function( fn ) {
		if( typeof fn !== 'function' ) {
			throw 'No callback function given';
		}
		using.push( fn );
		return self;
	};

	/**
	 * Adds the name of a detail descriptor required for defining an instance of this type.
	 *
	 * @param {string} keyWord
	 * // TODO: 2nd parameter for optional validation of the value.
	 * @returns {TypeSpec} self-reference
	 *
	 * TODO: might be that this should not be part of the TypeSpec. The information is only needed
	 *  when building the DSL for allowing e.g. modelDesigner.field( '...').as.instance().of( 'xxx').
	 *  So if this feature should be available in the DSL, then the information could be provided
	 *  separately. The information could also be generated by parsing the "use" function's toString().
	 */
	this.descriptor = function( keyWord ) {
		if( typeof keyWord !== 'string' || keyWord.length === 0 ) {
			throw 'Required keyword has to be a string';
		}
		descriptors.push( keyWord );
		return self;
	};

	/**
	 * Adds a validator associated with a name which can be used on values of this type.
	 *
	 * @param {string|string[]} name
	 * @param {function} validatorFn
	 * @returns {TypeSpec} self-reference
	 */
	this.validator = function( names, validatorFn ) {
		validators.validator.apply( validators, arguments );
		return self;
	};

	/**
	 * Returns or sets the validators available for this type.
	 *
	 * @param {Validators} validators
	 * @returns {Validators|TypeSpec} the type's validators or a self-reference if used as setter.
	 */
	this.validators = function( newValidators ) {
		if( !newValidators ) {
			return validators;
		}
		validators = newValidators;
	};

	/**
	 * For describing a property of values of this type.
	 *
	 * @param {string} name
	 * @param {TypeSpec} ofType
	 */
	this.property = function( name, ofType ) {
		// TODO: Type checks.
		properties[ name ] = ofType;
		return self;
	};
};
